// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/transport/grpc/proto/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	MiddleName    string                 `protobuf:"bytes,2,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Age           uint32                 `protobuf:"varint,7,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_internal_transport_grpc_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrationRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegistrationRequest) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *RegistrationRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegistrationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegistrationRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *RegistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegistrationRequest) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type RegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_internal_transport_grpc_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_internal_transport_grpc_proto_user_proto protoreflect.FileDescriptor

const file_internal_transport_grpc_proto_user_proto_rawDesc = "" +
	"\n" +
	"(internal/transport/grpc/proto/user.proto\x12\x04user\"\xd9\x01\n" +
	"\x13RegistrationRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vmiddle_name\x18\x02 \x01(\tR\n" +
	"middleName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\a \x01(\rR\x03age\"/\n" +
	"\x14RegistrationResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId2T\n" +
	"\vUserService\x12E\n" +
	"\fRegistration\x12\x19.user.RegistrationRequest\x1a\x1a.user.RegistrationResponseB\x0eZ\f../pb;userv1b\x06proto3"

var (
	file_internal_transport_grpc_proto_user_proto_rawDescOnce sync.Once
	file_internal_transport_grpc_proto_user_proto_rawDescData []byte
)

func file_internal_transport_grpc_proto_user_proto_rawDescGZIP() []byte {
	file_internal_transport_grpc_proto_user_proto_rawDescOnce.Do(func() {
		file_internal_transport_grpc_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_proto_user_proto_rawDesc), len(file_internal_transport_grpc_proto_user_proto_rawDesc)))
	})
	return file_internal_transport_grpc_proto_user_proto_rawDescData
}

var file_internal_transport_grpc_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_transport_grpc_proto_user_proto_goTypes = []any{
	(*RegistrationRequest)(nil),  // 0: user.RegistrationRequest
	(*RegistrationResponse)(nil), // 1: user.RegistrationResponse
}
var file_internal_transport_grpc_proto_user_proto_depIdxs = []int32{
	0, // 0: user.UserService.Registration:input_type -> user.RegistrationRequest
	1, // 1: user.UserService.Registration:output_type -> user.RegistrationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_transport_grpc_proto_user_proto_init() }
func file_internal_transport_grpc_proto_user_proto_init() {
	if File_internal_transport_grpc_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_proto_user_proto_rawDesc), len(file_internal_transport_grpc_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transport_grpc_proto_user_proto_goTypes,
		DependencyIndexes: file_internal_transport_grpc_proto_user_proto_depIdxs,
		MessageInfos:      file_internal_transport_grpc_proto_user_proto_msgTypes,
	}.Build()
	File_internal_transport_grpc_proto_user_proto = out.File
	file_internal_transport_grpc_proto_user_proto_goTypes = nil
	file_internal_transport_grpc_proto_user_proto_depIdxs = nil
}
